sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":99, \"username\":\"aaa\",\"password\":\"111\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.10.128
    port: 5672
    username: admin
    password: admin
        
server:
  port: 8101
  
eureka:
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
  instance:
    lease-renewal-interval-in-seconds: 30 #心跳间隔时间，默认 30 秒

=======
      defaultZone: http://eureka1:2001/eureka, http://eureka1:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
>>>>>>> branch 'master' of https://github.com/fubinjun/sp-config.git
